steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west3-docker.pkg.dev/qacc-video-recorder-2026/qacc-repo-eu/recording-worker:latest', '-f', 'apps/worker/Dockerfile.recording', '.']
images:
- 'europe-west3-docker.pkg.dev/qacc-video-recorder-2026/qacc-repo-eu/recording-worker:latest'
